### PR TITLE
Add repo option in __using__ macro

### PR DESCRIPTION
**Pull request by astery**
It gives the ability to use this in umbrella which uses commanded in multiple apps.

### CODE REVIEW

**Comment by slashdotdash** [comment]
Useful change, thanks @astery.

**Comment by slashdotdash** [comment]
I will publish this up to hex as v0.4.0

**Comment by slashdotdash** [comment]
Now available [on hex](https://hex.pm/packages/commanded_ecto_projections).  

I snuck in a new feature too, the [`after_update` callback](https://github.com/slashdotdash/commanded-ecto-projections#after_update-callback).

**Comment by astery** [comment]
Nice!

**Pull request merged**
